### ISSUE TITLE
How to create new transaction with reddsight-api?

### ISSUE THREAD

**Issue by RubberArchind** [reddcoin-project/reddsight-api#8]
Hello I'm confused when I want to create a new transaction programmatically, on the documentation page I only found broadcast transactions but no create transactions

**Comment by reddink** [comment]
To create a transaction programically, you will need to use the reddcore library.
reddcoin-project/reddcore-org

The reddsight and reddsight-api provide an interface into the blockchain, but not a way of creating and signing transactions.
You can use it to broadcast your signed transaction.

**Comment by RubberArchind** [comment]
Allright thank you.

**Comment by RubberArchind** [comment]
I found this website https://x-team.com/blog/reddcoin-nodejs/ and try to create transaction with that but when i broadcast the transaction it's return an error TX decode failed (code -22).

can you help me with that

**Comment by reddink** [comment]
Ok, the tutorial is close,
Except for 1 missing detail. Reddcoin transactions sign all the inputs then add the timestamp as the last field.
From the previous reddcore project, you can see that here.
https://github.com/reddcoin-project/reddcore-org/commit/f66a0605c57077bf9c88fbc92eafa8b1ea861179

How to help move you forward.

In terms of modernising libraries,
forking bitcore-lib and creating a reddcoin specific would seem the way to go

I know this doesnt solve your immediate issue, but it will push Reddcoin down the modernisation path.

**Comment by RubberArchind** [comment]
Ok, thanks for your support.
